<a href="https://colab.research.google.com/github/HebaHossam68/Fashion-MNIST/blob/main/Advanced_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import keras
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten
from keras.layers import Conv2D,MaxPool2D

In [2]:
(x_train,y_train),(x_test,y_test)=fashion_mnist.load_data()

In [3]:
img_rows,img_cols=28,28
if keras.backend.image_data_format()=='Channels first':
  x_train=x_train.reshape(x_train.shape[0],img_rows,img_cols,1)
  x_test=x_test.reshape(x_test.shape[0],img_rows,img_cols,1)
  input_shape=(img_rows,img_cols,1)
else:
  x_train=x_train.reshape(x_train.shape[0],img_rows,img_cols,1)
  x_test=x_test.reshape(x_test.shape[0],img_rows,img_cols,1)
  input_shape=(img_rows,img_cols,1)

x_train=x_train/255.0
x_test=x_test/255.0

print(x_train.shape)


(60000, 28, 28, 1)


In [4]:
print(y_train)

[9 0 0 ... 3 0 5]


In [5]:
y_train=keras.utils.to_categorical(y_train,10)
y_test=keras.utils.to_categorical(y_test,10)

In [6]:
print(y_train)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [10]:
print(y_train.shape)

(60000, 10)


In [11]:
print(y_test.shape)

(10000, 10)


In [7]:
model=Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=input_shape))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100,activation='relu'))
model.add(Dense(10,activation='softmax'))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 24, 24, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 12, 12, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 9216)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 100)            │       921,700 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 941,526 (3.59 MB)

 Trainable params: 941,526 (3.59 MB)

 Non-trainable params: 0 (0.00 B)

In [13]:
from keras.optimizers import SGD
opt=SGD(learning_rate=0.01,momentum=0.9)
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'])

In [14]:
model.fit(x_train,y_train,epochs=10,batch_size=32,verbose=1,validation_data=(x_test,y_test))

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.7544 - loss: 0.6717 - val_accuracy: 0.8707 - val_loss: 0.3565
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8913 - loss: 0.2997 - val_accuracy: 0.8920 - val_loss: 0.2947
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9110 - loss: 0.2410 - val_accuracy: 0.8856 - val_loss: 0.3172
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9227 - loss: 0.2059 - val_accuracy: 0.9094 - val_loss: 0.2588
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9325 - loss: 0.1759 - val_accuracy: 0.9078 - val_loss: 0.2636
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9449 - loss: 0.1467 - val_accuracy: 0.9078 - val_loss: 0.2649
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9522 - loss: 0.1298 - val_accuracy: 0.9178 - val_loss: 0.2494
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9601 - loss: 0.109

In [15]:
test_loss,test_acc=model.evaluate(x_test,y_test,verbose=0)
print('Test Loss : ',test_loss)
print('Test Accuracy : ',test_acc)

Test Loss :  0.30769702792167664
Test Accuracy :  0.9182999730110168


In [16]:
model.save('model.h5')
print('Saved')

Saved


In [26]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.models import load_model
import numpy as np


In [21]:
def load_image(file_name):
  img=load_img(file_name,color_mode="grayscale",target_size=(28,28))
  img=img_to_array(img)
  img=img.reshape(1,28,28,1)
  img=img.astype('float32')
  img=img/255.0
  return img

In [27]:
def run_example():
  img=load_image('/content/sample_image.png')
  model=load_model('/content/model.h5')
  result=model.predict(img)
  print(result)
  predicted_class=np.argmax(result,axis=1)
  print(predicted_class)

In [28]:
run_example()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step
[[3.6725785e-09 2.0233161e-11 9.9998379e-01 1.3309145e-12 1.6165350e-05
  5.1600120e-11 1.0752410e-08 2.9242654e-14 2.5156155e-10 1.0580257e-12]]
[2]
